### ISSUE TITLE
right icon no show

### ISSUE THREAD

**Issue by slsasa** [fateh999/react-native-paper-dropdown#46]

**Comment by VariabileAleatoria** [comment]
Same issue, "react-native-vector-icons" is installed because if I try to render a TextInput with an icon i.e.
```
<TextInput
            label="Password"
            secureTextEntry
            right={<TextInput.Icon icon="menu-up" />}
          />
```
It renders correctly, while the dropdown does not.
![image](https://user-images.githubusercontent.com/45683610/199205555-c9518a0f-d45a-4ac4-9748-983207ee289f.png)

Here a comparison of the two dropdowns taken from the example project in this repo versus the TextInput above

**Comment by ManishAdglobal360** [comment]
how we can change right icon?

**Comment by robin-farmx** [comment]
I am seeing the same issue with:

```
"react-native-paper": "^5.8.0",
"react-native-paper-dropdown": "^1.0.7",
"react-native-vector-icons": "^9.2.0",
```

Icons work with react native paper, but are not shown in the dropdown.

Has anyone else had success in resolving this issue?

**Comment by robin-farmx** [comment]
See: https://github.com/fateh999/react-native-paper-dropdown/issues/91
